<html>
          <head></head>
          <body>
            <h2>Unit Tests Timed Out for Pull Request at ciuser/arbitrary</h2>
<p>A repository monitored by the Continuous Integration server has
  timed out while executing its unit tests.</p>
<p>
  <h3><a href="http://github.com/ciuser/arbitrary">ciuser/arbitrary</a> <a href="__pullurl__">#__pullnum__</a></h3>
  Unit testing description of arbitrary.
</p>
<h3>Unit Test Results</h3>

<table>
  <tbody>
    <tr>
      <th>Command</th>
      <th>Start</th>
      <th>End</th>
      <th>Code</th>
    </tr>
    <tr>
      <td>first tests/a.py</td>
      <td>07/14/2005 12:30</td>
      <td>07/14/2005 12:31</td>
      <td>0</td>
    </tr>
    <tr>
      <td>@CUSTBIN tests/scripts.py</td>
      <td>07/14/2005 12:30</td>
      <td>07/14/2005 12:31</td>
      <td>1</td>
    </tr>
    <tr>
      <td>cd @CUSTPATH; path tests/builders.py</td>
      <td>07/14/2005 12:30</td>
      <td>07/14/2005 12:31</td>
      <td>2</td>
    </tr>
  </tbody>
</table>__

<p>Unit tests ran in "/Users/trunks/codes/ci/tests/repo".<br />
Online details available at <a href="__wikiurl__">the wiki</a>.</p>

<p>If you have any questions, please contact the owner of the repository:</p>
<p>
  <a href="http://usercontent.github.com/ciuser">ciuser</a><br />
  <a href="mailto:__useremail">ciuser@gmail.com</a>
</p>
<p>
Kind Regards,<br />
CI Bot
</p>
  
          </body>
        </html>